# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(175, 69)
    self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
    self.verticalLayout.setObjectName("verticalLayout")
    self.HL1 = QtWidgets.QHBoxLayout()
    self.HL1.setObjectName("HL1")
    self.lblValor = QtWidgets.QLabel(Dialog)
    self.lblValor.setObjectName("lblValor")
    self.HL1.addWidget(self.lblValor)
    self.txtValor = QtWidgets.QLineEdit(Dialog)
    self.txtValor.setText("")
    self.txtValor.setObjectName("txtValor")
    self.HL1.addWidget(self.txtValor)
    self.verticalLayout.addLayout(self.HL1)
    self.btnOk = QtWidgets.QPushButton(Dialog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.btnOk.sizePolicy().hasHeightForWidth())
    self.btnOk.setSizePolicy(sizePolicy)
    self.btnOk.setObjectName("btnOk")
    self.verticalLayout.addWidget(self.btnOk, 0, QtCore.Qt.AlignHCenter)

    self.retranslateUi(Dialog)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    self.lblValor.setText(_translate("Dialog", "Valor:"))
    self.btnOk.setText(_translate("Dialog", "&Ok"))
